# Generated by Django 5.1.4 on 2025-04-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hostelstudent_user_address_user_branch_user_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_reset_password',
            field=models.BooleanField(default=True),
        ),
    ]
