# Generated by Django 5.1.4 on 2025-04-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_must_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='must_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
