# Generated by Django 5.1.4 on 2025-04-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_must_reset_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostelStudent',
        ),
        migrations.AddField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
